=== ringga-bf/Test_Scan_Id/app/src/main/assets/idcardocr/IDCARDS/IDCARD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<!ELEMENT vecLine ((CLine+))>
<!ELEMENT vecDeriveUnit ((CDeriveUnit*))>
<!ELEMENT vecFlagFind ((CFlagFind*))>
<!ELEMENT vecRegion ((CRegion*))>
<!ELEMENT vecSubTemplate ((CSubTemplate*))>
<!ELEMENT vecRecogUnit ((CRecogUnit*))>
<!ELEMENT vecProcessMode ((CAutoProcess*))>
<!ELEMENT vecAutoProcess ((vecProcessMode*))>
<!ELEMENT vecProcessImage ((CProcessImage*))>
<!ELEMENT vecLineKeyWord ((CKeyWord*))>
<!ELEMENT vecImageLightType ((LIGHTTYPE+))>
<!ELEMENT vecAnchor ((CAnchor*))>
<!ELEMENT vecCLocateAnchor ((CLocateAnchor*))>
<!ELEMENT vecAnchorLocateInfo ((CAnchorLocateInfo*))>
<!ELEMENT vecCharRatio ((CCharRatio*))>
<!ELEMENT vecRegionKernal ((CRegionKernalInfo*))>
<!ELEMENT vecDLKernalInfo ((CDLKernalInfo*))>
<!ELEMENT vecKernal ((CKernalInfo*))>
<!ELEMENT vecCLocateMethod ((CLocateMethod+))>
<!ELEMENT vecCReplaceChar ((CReplaceChar+))>
<!ELEMENT vecCInsertChar ((CInsertChar*))>
<!ELEMENT vecOutPutResult ((COutPutResult*))>
<!ELEMENT vecMergeUnit ((CMergeUnit*))>
<!ELEMENT CMergeUnit EMPTY>
<!ATTLIST CMergeUnit 
  nDestUnitIndex CDATA #REQUIRED
  nDestUnitType (1|2|3|4) #REQUIRED
  nSrcUnitIndex CDATA #REQUIRED
  nSrcUnitType  CDATA #REQUIRED
  strSrc        CDATA #REQUIRED
  strDest       CDATA #REQUIRED
  nProcessPos   CDATA #REQUIRED
  bMeet         CDATA #REQUIRED
  bSynchronous  CDATA #REQUIRED 
  nOperateType  CDATA #REQUIRED
  nSrcUintStart CDATA #IMPLIED
  nSrcUintEnd   CDATA #IMPLIED
  >

<!ELEMENT vecDetectTextLine ((CDetectTextLine*))>
<!ELEMENT CDetectTextLine ((vecDLKernalInfo*))>
<!ATTLIST CDetectTextLine 
  nDetectType   (0|1) #REQUIRED
  nMainID       CDATA #IMPLIED
  nSubID        CDATA #IMPLIED
  strModel      CDATA #IMPLIED
  >
  
<!ELEMENT COutPutResult ((CFormatInfo?,COand0Classify?))>
<!ATTLIST COutPutResult
	nIndex CDATA #REQUIRED
	cellRecogType (0|1|2|3|4|5|6|7|8|9|10|11|13|12|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43) #REQUIRED
	cellName CDATA #REQUIRED
	nOutputThreshold CDATA #REQUIRED
	nOutputNumber CDATA #REQUIRED
	bFormatResult (0|1)  #REQUIRED
	bRecogOand0 CDATA #IMPLIED
	bMainField (0|1)  #IMPLIED 
	cellNameEng CDATA #IMPLIED
	nRejectThresh CDATA #IMPLIED
	bCountryCode CDATA #IMPLIED
	nContentType CDATA #IMPLIED
>
<!ELEMENT CFormatInfo ((vecCReplaceChar?))>
<!ATTLIST CFormatInfo
	strInFormat CDATA #REQUIRED
	strOutFormat CDATA #REQUIRED
	strDefault CDATA #REQUIRED
>
<!ELEMENT CReplaceChar EMPTY>
<!ATTLIST CReplaceChar
	oldChar CDATA #REQUIRED
	newChar CDATA #REQUIRED
>
<!ELEMENT CInsertChar EMPTY>
<!ATTLIST CInsertChar
	nInsertType (0|1|2|3) #REQUIRED
	nMinSpace CDATA #REQUIRED
	nMaxSpce CDATA #REQUIRED
	nCharPos CDATA #REQUIRED
	strInsert CDATA #REQUIRED
>
<!ELEMENT COand0Classify EMPTY>
<!ATTLIST COand0Classify
strAllIndex CDATA #REQUIRED>

<!ELEMENT CLocateMethod ((vecProcessImage?))>
<!ATTLIST CLocateMethod
	nLocateMethod (0|1|2|3|4|5) #REQUIRED
	nMainID CDATA #IMPLIED
	nSubID CDATA #IMPLIED
>
<!ELEMENT CLocateRecogUnit ((vecAnchorLocateInfo?))>
<!ATTLIST CLocateRecogUnit
	bStart (0|1) #REQUIRED
	nStartIndexInChar CDATA #REQUIRED
	bEnd (0|1) #REQUIRED
	nEndIndexInChar CDATA #REQUIRED
>
<!ELEMENT CDeriveUnit ((vecFlagFind?))>
<!ATTLIST CDeriveUnit
	nIndex CDATA #REQUIRED
	nSrcRecogUnitIndex CDATA #REQUIRED
	nStartCharIndex CDATA #REQUIRED
	nEndCharIndex CDATA #REQUIRED
	nType CDATA  #IMPLIED 
>

<!ELEMENT CRecogInfo ((CLocateInfo,vecKernal))>
<!ATTLIST CRecogInfo
	bMatchRegExp (0|1) #REQUIRED
	charOrder CDATA #IMPLIED
	bConfirmParams (0|1) #REQUIRED
	bIgnorePoint (0|1) #REQUIRED
	nMaxPointWidth  CDATA #REQUIRED
	nMaxPointHeight CDATA #REQUIRED
	bDetectLine (0|1) #IMPLIED 
	nKernelType (0|1) #IMPLIED 
	nProcessOrder (0|1) #IMPLIED 
>
<!ELEMENT vecRegionRecogInfo ((CRegionRecogInfo*))>
<!ATTLIST vecRegionRecogInfo
	nProcessOrder  (0|1) #REQUIRED
>
<!ELEMENT CRegionRecogInfo ((vecProcessImage?,vecRegionKernal?))>
<!ATTLIST CRegionRecogInfo
	nKernelType CDATA #REQUIRED
	nMinElementNum  CDATA #REQUIRED
	nMaxElementNum CDATA #REQUIRED 
>
<!ELEMENT positionPlus EMPTY>
<!ATTLIST positionPlus
	nBottomPlus CDATA #REQUIRED
	nLeftPlus CDATA #REQUIRED
	nRightPlus CDATA #REQUIRED
	nTopPlus CDATA #REQUIRED
>
<!ELEMENT CFlagFind EMPTY>
<!ATTLIST CFlagFind
	nFindType (0|1) #REQUIRED
	strFlag CDATA #REQUIRED
	bStart (0|1) #REQUIRED
	nStartIndex CDATA #REQUIRED
	nNum CDATA #REQUIRED
	nPosType (0|1) #REQUIRED
	nIndexPlus CDATA #REQUIRED
>
<!ELEMENT CLocateRegion ((vecProcessImage?, RECT, vecAnchorLocateInfo, vecCLocateAnchor?))>
<!ATTLIST CLocateRegion
	bAccurateLocate (0|1) #REQUIRED
>
<!ELEMENT CLocateLine ((RECT,RECT,CLocateInfo, positionPlus?))>
<!ELEMENT CLocateInfo ((vecCLocateMethod))>
<!ATTLIST CLocateInfo
	nNumType CDATA #REQUIRED
	nMaxElementNum CDATA #REQUIRED
	nMaxHeight CDATA #REQUIRED
	nMaxSpace CDATA #REQUIRED
	nMaxWidth CDATA #REQUIRED
	nMinElementNum CDATA #REQUIRED
	nMinHeight CDATA #REQUIRED
	nMinSpace CDATA #REQUIRED
	nMinWidth CDATA #REQUIRED
	nMinWHRatio CDATA #REQUIRED
	nMaxWHRatio CDATA #REQUIRED
    nSplitWHRatio CDATA #REQUIRED
    bSplit (0|1) #REQUIRED
	bWidth (0|1) #REQUIRED
	bHeight (0|1) #REQUIRED
	bSpace (0|1) #REQUIRED
	bPostProcess (0|1) #REQUIRED
	bRemoveLineNoise (0|1) #REQUIRED
	bEraseStart (0|1) #REQUIRED
	bCheckSpace (0|1) #IMPLIED
	bAngleCorrection (0|1) #IMPLIED
	bCheckHeight (0|1|2) #IMPLIED
	nStandardHeight CDATA #IMPLIED 
	bInpaintLine (0|1|2) #IMPLIED 
	bRemoveInValidLine (0|1) #IMPLIED
	nSmooth (0|1|2) #IMPLIED
	
>
<!ELEMENT CRegion ((vecProcessImage?,vecImageLightType, CLocateRegion, CLocateLine?, vecLine?))>
<!ATTLIST CRegion
	nIndex CDATA #REQUIRED
	nProcessOrder CDATA #REQUIRED
	nRegionType CDATA #REQUIRED
>
<!ELEMENT CSubTemplate ((vecDetectTextLine*, vecRegion*, vecDeriveUnit*,vecAnchor*,vecMergeUnit*,vecOutPutResult*))>
<!ATTLIST CSubTemplate
	nSubID CDATA #REQUIRED
	chDocumentName CDATA #IMPLIED
	engDocumentName CDATA #IMPLIED
	bVariableName CDATA #IMPLIED
>
<!ELEMENT RECT EMPTY>
<!ATTLIST RECT
	Bottom CDATA #REQUIRED
	Left CDATA #REQUIRED
	Right CDATA #REQUIRED
	Top CDATA #REQUIRED
>
<!ELEMENT BINARYPARAM EMPTY>
<!ATTLIST BINARYPARAM
	nBlockNum CDATA #REQUIRED
	nMethod CDATA #REQUIRED
>
<!ELEMENT CRecogUnit ((CLocateRecogUnit?, vecRecogInfo?, CRecogInfo?,vecCInsertChar?))>
<!ATTLIST CRecogUnit
	bLocate (0|1) #REQUIRED
	bRecog (0|1) #REQUIRED
	nIndex CDATA #REQUIRED
>

<!ATTLIST vecProcessMode
nMode (0|1) #REQUIRED>

<!ELEMENT CProcessImage ((CTrueColorToGrayEx?,CGrayToBinaryEx?,CEraseBlackBorderEx?,CTiltCorrection?,CBlurAverage?,CCropImage?,CInvertImage?,CMedianFilterEx?,CRotateEx?,CAutoCropImage?,CGaussianFilter?,CImageResizer?,CReSizeImage?,CReSizeImageEx?,CAutoRotateInTemplate?,CAutoCropInTemplate?,CHistogramEqualization?,CIDCardAutoProcess?,CRotateEx?))>
<!ATTLIST CProcessImage
	processType CDATA #REQUIRED
>

<!ELEMENT CReSizeImage EMPTY>
<!ATTLIST CReSizeImage
nWidth CDATA #REQUIRED
nHeight CDATA #REQUIRED>

<!ELEMENT CImageResizer EMPTY>
<!ATTLIST CImageResizer
nScaleX CDATA #REQUIRED
nScaleY CDATA #REQUIRED>


<!ELEMENT CAutoProcess
((CIDCardAutoProcessEx?,CIDCardAutoProcessEx2?,PerspectiveTransform?,PerspectiveTransformEx?,CIDCardAutoProcess?,CTrueColorToGrayEx?,CEraseBlackBorderEx?,PerspectiveDLModel?,PerspectiveObjDectIDCard?,PerspectiveEightCornersDL?))>
<!ATTLIST CAutoProcess
	processType CDATA #REQUIRED
>

<!ELEMENT CRotateEx ((RECT?))>
<!ATTLIST CRotateEx 
	nRotateType (0|1|2|3|4) #REQUIRED
>
<!ELEMENT CTiltCorrection EMPTY>
<!ATTLIST CTiltCorrection
	bSameSize (0|1) #REQUIRED
	nFilledType (0|1) #REQUIRED
	nMinAngle CDATA #REQUIRED
	nMaxAngle CDATA #REQUIRED
>
<!ELEMENT CTrueColorToGrayEx ((RECT))>
<!ATTLIST CTrueColorToGrayEx
	nFilter CDATA #REQUIRED
>
<!ELEMENT CGaussianFilter EMPTY>
<!ATTLIST CGaussianFilter
	fSigma CDATA #REQUIRED
>
<!ELEMENT CAutoRotateInTemplate EMPTY>
<!ATTLIST CAutoRotateInTemplate
	nRotateType CDATA #REQUIRED
>
<!ELEMENT CAutoCropInTemplate EMPTY>
<!ATTLIST CAutoCropInTemplate
	nCropType CDATA #REQUIRED
>
<!ELEMENT CHistogramEqualization EMPTY>
<!ATTLIST CHistogramEqualization
	nType CDATA #REQUIRED
>

<!ELEMENT CReSizeImageEx EMPTY>
<!ATTLIST CReSizeImageEx
	nWidth CDATA #REQUIRED
	nHeight CDATA #REQUIRED
>

<!ELEMENT CIDCardAutoProcess EMPTY>
<!ATTLIST CIDCardAutoProcess
    nCropType CDATA #REQUIRED
    nRotateType CDATA #REQUIRED
	bSameSize (0|1) #REQUIRED
	nFilledType (0|1) #REQUIRED
	nMinAngle CDATA #REQUIRED
	nMaxAngle CDATA #REQUIRED
>

<!ELEMENT CIDCardAutoProcessEx EMPTY>
<!ATTLIST CIDCardAutoProcessEx
    nCropType CDATA #REQUIRED
    bCrop CDATA #REQUIRED 
    nRotateType CDATA #REQUIRED 
    bRotate CDATA #REQUIRED 
    bTilt CDATA #REQUIRED
    bResize CDATA #REQUIRED 
	bSameSize (0|1) #REQUIRED 
	nFilledType (0|1) #REQUIRED
	nMinAngle CDATA #REQUIRED
	nMaxAngle CDATA #REQUIRED 
	nWidth CDATA #IMPLIED
	nHeight CDATA #IMPLIED 
>

<!ELEMENT CIDCardAutoProcessEx2 EMPTY>
<!ATTLIST CIDCardAutoProcessEx2
    nCropType CDATA #REQUIRED   
	nFilledType (0|1) #REQUIRED
	nMinAngle CDATA #REQUIRED
	nMaxAngle CDATA #REQUIRED
	bIs180Rotate (0|1) #REQUIRED 
	bIsValid (0|1) #REQUIRED  
	bSameSize (0|1) #REQUIRED 
	bTilt (0|1) #IMPLIED 
>

<!ELEMENT PerspectiveTransform EMPTY>
<!ATTLIST PerspectiveTransform
    nType CDATA #REQUIRED   
	nWidth CDATA #REQUIRED
	nHeight CDATA #REQUIRED 
	bIs180Rotate (0|1) #IMPLIED
	bIsValid (0|1) #IMPLIED
	nOffsetLeft CDATA #IMPLIED
	nOffsetRight CDATA #IMPLIED 
	nOffsetTop CDATA #IMPLIED 
	nOffsetBottom CDATA #IMPLIED 
>

<!ELEMENT PerspectiveTransformEx EMPTY>
<!ATTLIST PerspectiveTransformEx
    nType CDATA #REQUIRED   
	nWidth CDATA #REQUIRED
	nHeight CDATA #REQUIRED 
>

<!ELEMENT PerspectiveEightCornersDL ((vecDLKernalInfo*))>
<!ATTLIST PerspectiveEightCornersDL
    nType CDATA #REQUIRED   
	nWidth CDATA #REQUIRED
	nHeight CDATA #REQUIRED 
>

<!ELEMENT CBlurAverage EMPTY>
<!ATTLIST CBlurAverage
	nType CDATA #REQUIRED
>
<!ELEMENT vecBinaryParam ((BINARYPARAM+))>
<!ELEMENT CGrayToBinaryEx ((vecBinaryParam,RECT))>

<!ELEMENT CEraseBlackBorderEx ((RECT,RECT))>
<!ATTLIST CEraseBlackBorderEx
>
<!ELEMENT PerspectiveDLModel EMPTY>
<!ATTLIST PerspectiveDLModel
	nType CDATA #REQUIRED
	nWidth CDATA #REQUIRED
	nHeight CDATA #REQUIRED
>
<!ELEMENT PerspectiveObjDectIDCard EMPTY>
<!ATTLIST PerspectiveObjDectIDCard
	nType CDATA #REQUIRED
	nWidth CDATA #REQUIRED
	nHeight CDATA #REQUIRED
>

<!ELEMENT CInvertImage ((RECT))>
<!ATTLIST CInvertImage
>
<!ELEMENT CMedianFilterEx ((RECT))>
<!ATTLIST CMedianFilterEx
>
<!ELEMENT CAutoCropImage ((RECT))>
<!ATTLIST CAutoCropImage
>
<!ELEMENT CLine ((RECT?,CReconvertInfo?,vecRecogInfo?, vecRecogUnit?, vecLineKeyWord?, vecCLocateAnchor?))>
<!ATTLIST CLine
	bEndOffset (0|1) #REQUIRED
	bStartOffset (0|1) #REQUIRED
	nIndex CDATA #REQUIRED
	bExist (0|1) #REQUIRED
	bNeedRecog (0|1) #REQUIRED
	nCheckKeyWord CDATA #REQUIRED
>

<!ELEMENT vecRecogInfo ((vecRegionRecogInfo?,CRecogInfo?))>
<!ELEMENT CReconvertInfo EMPTY>
<!ATTLIST CReconvertInfo
    nPosX CDATA #REQUIRED
    nPosY CDATA #REQUIRED
    nCharWidth CDATA #REQUIRED
    nCharHeight CDATA #REQUIRED
    nWHRatio CDATA #REQUIRED
    strContent CDATA #REQUIRED
    nThreshold CDATA #REQUIRED 
>
<!ELEMENT LIGHTTYPE (#PCDATA)>
<!ELEMENT CKeyWord ((vecCLocateAnchor))>
<!ATTLIST CKeyWord
	nConfirmType (0|1|2|3) #REQUIRED
	content CDATA #REQUIRED
	nMinWidth CDATA #REQUIRED
	nMaxWidth CDATA #REQUIRED
	nMinHeight CDATA #REQUIRED
	nMaxHeight CDATA #REQUIRED
>
<!ELEMENT IDCARD ((vecProcessImage?,CIDCardTemplate*,TemplatePath*))>

<!ELEMENT CIDCardTemplate ((vecAutoProcess?, vecProcessImage, vecDetectTextLine*, vecRegion?, vecDeriveUnit*,vecAnchor?,vecOutPutResult,vecMergeUnit?,vecSubTemplate?))>
<!ATTLIST CIDCardTemplate
	chDocumentName CDATA #REQUIRED
	imageSizeType (0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|18|21) #REQUIRED
	nMainDocumentID CDATA #REQUIRED
	engDocumentName CDATA #IMPLIED
>
<!ELEMENT TemplatePath (#PCDATA)>
<!ELEMENT CAnchor EMPTY>
<!ATTLIST CAnchor
	anchorPos CDATA #REQUIRED
	nMinPos CDATA #REQUIRED
	nMaxPos CDATA #REQUIRED
	anchorType (0|1|2|3|4|5|6) #REQUIRED
	bEnable (0|1) #REQUIRED
	nIndex CDATA #REQUIRED
	bInherited (0|1) #IMPLIED
>
<!ELEMENT CLocateAnchor EMPTY>
<!ATTLIST CLocateAnchor
	nDisToAnchor CDATA #REQUIRED
	nAnchorIndex CDATA #REQUIRED
	anchorType (0|1|2|3|4|5|6) #REQUIRED
>
<!ELEMENT CAnchorLocateInfo EMPTY>
<!ATTLIST CAnchorLocateInfo
	nAnchorIndex CDATA #REQUIRED
	nDisToAnchor CDATA #REQUIRED
	anchorType (0|1|2|3|4) #REQUIRED
>
<!ELEMENT CKernalInfo ((vecCharRatio?))>
<!ATTLIST CKernalInfo
	kernalMainType (1|2|3|10) #REQUIRED
	strFilterPlus CDATA ""
	nFillingMethod CDATA ""
	nFilterType CDATA ""
	nRecogImgeType (0|1) #REQUIRED
	nKernalSubType CDATA #REQUIRED
	nRecogType (0|1) #REQUIRED
>
<!ELEMENT CRegionKernalInfo ((vecDLKernalInfo?))>
<!ATTLIST CRegionKernalInfo
	kernalMainType (4|5|6|7|8|9) #REQUIRED
	nKernalSubType CDATA #IMPLIED
	strFilterPlus CDATA ""
	nFillingMethod CDATA ""
	nFilterType CDATA ""
	nRecogType (0|1) #REQUIRED
	nMainID CDATA #IMPLIED
>

<!ELEMENT CDLKernalInfo EMPTY>
<!ATTLIST CDLKernalInfo
	nType CDATA #IMPLIED
	nID CDATA #IMPLIED
	nIndex CDATA #IMPLIED
	strModel CDATA #IMPLIED
    nRecogImgeType (0|1|2) #REQUIRED
>

<!ELEMENT CCharRatio EMPTY>
<!ATTLIST CCharRatio
	charType (0|1|2|3|4|10) #REQUIRED
	nWHRatio CDATA #REQUIRED
	strChars CDATA #REQUIRED
>
<!ELEMENT CCropImage ((RECT))>
<!ATTLIST CCropImage
	nMinSrcWidth CDATA #REQUIRED
	nMinSrcHeight CDATA #REQUIRED
	nUnitType (0|1) #REQUIRED
	nRotateType CDATA #REQUIRED
>

=== ringga-bf/Test_Scan_Id/app/src/main/assets/idcardocr/IDCARDV/2081.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE IDCARD SYSTEM "IDCARD.dtd">
<IDCARD>
    <CIDCardTemplate nMainDocumentID="2081" chDocumentName="埃及身份证-照片页" engDocumentName="Egypt Resident Identity Card  Portrait Page" imageSizeType="2">
        <vecProcessImage>
            <CProcessImage processType="3">
                <CEraseBlackBorderEx>
                    <!--processRect要检测黑边的区域-->
                    <RECT Left="0" Top="0" Right="10000" Bottom="10000"/>
                    <!--unProcessRect在要检测的区域里，能够确定的不需要检测黑边的部分，
					也就是说这个区域肯定没有黑边存在，用来提高检测效率-->
                    <RECT Left="2000" Top="2000" Right="8900" Bottom="8000"/>
                </CEraseBlackBorderEx>
            </CProcessImage>
        </vecProcessImage>
        <vecRegion>
            <CRegion nIndex="0" nRegionType="0" nProcessOrder="0">
                <!--处理该区域需要的图像信息的光的类型-->
                <vecImageLightType>
                    <!--1:可见光图;2:红外光图;4:紫外光图 -->
                    <LIGHTTYPE>1</LIGHTTYPE>
                </vecImageLightType>
                <!--定义区域的定位信息,如果是头像区域还需要进一步精确定位，识别区域就不用了-->
                <!--bAccurateLocate为1表示需要进一步精确定位,0代表不需要-->
                <CLocateRegion bAccurateLocate="1">
                    <!--在定位前进行的预处理信息，一般是二值化-->
                    <vecProcessImage>
                        <CProcessImage processType="1">
                            <CTrueColorToGrayEx nFilter="0">
                                <RECT Top="0" Right="0" Bottom="0" Left="0"/>
                            </CTrueColorToGrayEx>
                        </CProcessImage>
                    </vecProcessImage>
                    <!--rcMinRect:指定定位区域的最小范围，即定位后的区域范围必须包含这个区域-->
                    <RECT Left="300" Top="900" Right="2400" Bottom="6000"/>
                    <vecAnchorLocateInfo>
                        <!--nDisToAnchor的值也是整图的百分比*10000计算出来的-->
                        <CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="200" anchorType="1"/>
                        <CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="3300" anchorType="2"/>
                        <CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="500" anchorType="3"/>
                        <CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="6300" anchorType="4"/>
                    </vecAnchorLocateInfo>
                    <!--该区域定义的区域类型基准点的信息-->
                    <vecCLocateAnchor>
                        <CLocateAnchor nDisToAnchor="0" nAnchorIndex="1" anchorType="1"/>
                        <CLocateAnchor nDisToAnchor="0" nAnchorIndex="2" anchorType="4"/>
                        <CLocateAnchor nDisToAnchor="0" nAnchorIndex="3" anchorType="3"/>
                    </vecCLocateAnchor>
                </CLocateRegion>
                <!--区域内定位行的信息-->
            </CRegion>
			<!-- 身份证号 -->
            <CRegion nIndex="1" nRegionType="1" nProcessOrder="1">
                <!--处理该区域需要的图像信息的光的类型-->
                <vecImageLightType>
                    <!--1:可见光图;2:红外光图;4:紫外光图 -->
                    <LIGHTTYPE>2</LIGHTTYPE>
                    <LIGHTTYPE>1</LIGHTTYPE>
                </vecImageLightType>
                <!--定义区域的定位信息,如果是头像区域还需要进一步精确定位，识别区域就不用了-->
                <!--bAccurateLocate为1表示需要进一步精确定位,0代表不需要-->
                <CLocateRegion bAccurateLocate="0">
                    <vecProcessImage/>
                    <!--rcMinRect:指定定位区域的最小范围，即定位后的区域范围必须包含这个区域-->
                    <RECT Left="9999" Top="9999" Right="0" Bottom="0"/>
                    <vecAnchorLocateInfo>
                        <!--nDisToAnchor的值也是整图的百分比*10000计算出来的-->
                        <CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="3870" anchorType="1"/>
                        <CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="9970" anchorType="2"/>
                        <CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="7435" anchorType="3"/>
                        <CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="8894" anchorType="4"/>
                    </vecAnchorLocateInfo>
                    <!--该区域定义的区域类型基准点的信息-->
                    <vecCLocateAnchor/>
                </CLocateRegion>
                <CLocateLine>
                    <!--rcHorizontal：进行行的左右边界定位时的区域范围，坐标单位为所在区域的百分比*100-->
                    <RECT Left="0" Top="0" Right="100" Bottom="100"/>
                    <!--rcVertical：进行行的上下边界定位时的区域范围，坐标单位为所在区域的百分比*100-->
                    <RECT Left="0" Top="0" Right="90" Bottom="100"/>
                    <CLocateInfo bEraseStart="0" nMinWHRatio="0" nMaxWHRatio="160" nSplitWHRatio="2000" bSplit="0" nNumType="0" bSpace="0" bWidth="0" bHeight="0" bRemoveLineNoise="0" nMinElementNum="1" nMaxElementNum="1" nMinWidth="4000" nMaxWidth="8000" nMaxHeight="700" nMinHeight="420" nMinSpace="0" nMaxSpace="0" bPostProcess="0">
                        <vecCLocateMethod>
                            <CLocateMethod nLocateMethod="1">
                                            <vecProcessImage>
                                                <CProcessImage processType="1">
                                                    <CTrueColorToGrayEx nFilter="0">
                                                        <RECT Top="0" Right="0" Bottom="0" Left="0"/>
                                                    </CTrueColorToGrayEx>
                                                </CProcessImage>
                                                <CProcessImage processType="2">
                                                    <CGrayToBinaryEx>
                                                        <vecBinaryParam>
                                                            <BINARYPARAM nBlockNum="1" nMethod="1"/>
                                                        </vecBinaryParam>
                                                        <RECT Left="0" Top="0" Right="0" Bottom="0"/>
                                                    </CGrayToBinaryEx>
                                                </CProcessImage>
                                            </vecProcessImage>
                                        </CLocateMethod>
                            <CLocateMethod nLocateMethod="0">
                                <!--在定位前进行的预处理信息，一般是二值化-->
                                <vecProcessImage>
                                    <CProcessImage processType="1">
                                        <CTrueColorToGrayEx nFilter="0">
                                            <RECT Top="0" Right="0" Bottom="0" Left="0"/>
                                        </CTrueColorToGrayEx>
                                    </CProcessImage>
                                </vecProcessImage>
                            </CLocateMethod>
                            </vecCLocateMethod>
                    </CLocateInfo>
                    <positionPlus nLeftPlus="-160" nRightPlus="160" nTopPlus="-160" nBottomPlus="160"/>
                </CLocateLine>
                <vecLine>
                    <CLine nIndex="0" bStartOffset="0" bEndOffset="1" bExist="1" bNeedRecog="1" nCheckKeyWord="0">
                        <RECT Left="0" Top="0" Right="0" Bottom="0"/>
                        <vecRecogInfo>
                            <vecRegionRecogInfo nProcessOrder="1">
								<CRegionRecogInfo nKernelType="1" nMinElementNum="0" nMaxElementNum="-1">
									<vecRegionKernal>
										<CRegionKernalInfo kernalMainType="5" nMainID="2081" nRecogType="0">
											<vecDLKernalInfo>
												<CDLKernalInfo nType="0" nID="14" nIndex="0" nTYType="0" nParam1="0" nParam2="0" strModel="alb_cpu" nRecogImgeType="2"/>
												<CDLKernalInfo nType="1" nID="14" nIndex="1" nTYType="0" nParam1="0" nParam2="0" strModel="alb_gpu" nRecogImgeType="2"/>
											</vecDLKernalInfo>
										</CRegionKernalInfo>
									</vecRegionKernal>
								</CRegionRecogInfo>
							</vecRegionRecogInfo>
                            <CRecogInfo bIgnorePoint="0" nMaxPointWidth="0" nMaxPointHeight="0" bMatchRegExp="0" charOrder="\D{17}[\DX]" bConfirmParams="0" nProcessOrder="0" nKernelType="0">
                                <CLocateInfo bEraseStart="0" nMinWHRatio="0" nMaxWHRatio="100" nSplitWHRatio="2000" bSplit="0" nNumType="0" bSpace="0" bWidth="0" bHeight="0" bRemoveLineNoise="0" nMinElementNum="14" nMaxElementNum="14" nMinWidth="20" nMaxWidth="500" nMinHeight="20" nMaxHeight="620" nMinSpace="0" nMaxSpace="500" bPostProcess="1">
                                    <vecCLocateMethod>
                                        <CLocateMethod nLocateMethod="1">
                                            <vecProcessImage>
                                                <CProcessImage processType="1">
                                                    <CTrueColorToGrayEx nFilter="0">
                                                        <RECT Top="0" Right="0" Bottom="0" Left="0"/>
                                                    </CTrueColorToGrayEx>
                                                </CProcessImage>
                                                <CProcessImage processType="2">
                                                    <CGrayToBinaryEx>
                                                        <vecBinaryParam>
                                                            <BINARYPARAM nBlockNum="1" nMethod="6"/>
                                                        </vecBinaryParam>
                                                        <!--processRect-->
                                                        <RECT Left="0" Top="0" Right="0" Bottom="0"/>
                                                    </CGrayToBinaryEx>
                                                </CProcessImage>
                                            </vecProcessImage>
                                        </CLocateMethod>
                                    </vecCLocateMethod>
                                </CLocateInfo>
                                <vecKernal>
